#+TITLE: Astoria
#+AUTHOR: Adrian Eichelbaum
#+STARTUP: showall

*  Initial Ideas
+ Group is part of a resistence group in nazi leipzig
+ for first "season" they ultimatly have to free the MIMO (Mitteldeutsche Motorenwerke)
+ for that they have to complete several prep missions, like rescuing CIs, gathering supplies, recon,...
+ there is magic in this world
+ plays around 1945
+ gang has their chars with their backstory, magic allowed, need a reason, whey they not at the front

* Backgroundinformation

** 03.12.1943 bombing of Leizpig
 + Royal Air Force
 + in the early morning
 + 1800 deaths
 + large parts of the city center destroyed
 + facotrys experienced shortfalls and were moved or decentralized **(abilty to attack such a replacement)**

** Erla Maschinenwerke
 + aircraft facotry (produced the Messerschmitt Bf109)
 + three locations: Mockau, Abtnaundorf, Heiterblick
 + one of the largest producers

** Mitteldeutsche Motorenwerke (MIMO)
 + produced planemotors
 + https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs3.amazonaws.com%2Fgs-geo-images%2Fc91fd673-8f5a-4056-a6f4-9d7c928dcdd4.jpg&f=1&nofb=1

** Leizpiger Meuten
 + https://blog.zeit.de/stoerungsmelder/2012/03/15/der-vergessene-widerstand-leipzigs-jugend-gegen-hitler_8255
 + up to 1500 teenagers as oppositon to the nazis and the HJ
 + mostly between 14 and 18
 + moslty out of the working class with sozialdemocratic or communistic parents
 + wore short leathertrousers and chequered hemden, colorful neckties
 + badges were very important, for example skull-badges, or marriage rings, withour being married
 + made up out of man and woman, but woman were degraded from the Stasi to sexual objects
 + very good relations with other groups
 + if they met the HJ, dann krieg
 + Gestapo at first did not see them as a threat, but later prosecuted them
 + wanted to scare the masses by sentencing a few for treason, a few of them landed in KZ's, some in **prison (maybe rescue one of them)** for a few years
 + but no effect, so they started to execute mass arrests and build teenager KZ's (hard work, reeducation)

* Kommunitischer Wiederstand
+ http://prisma.blogsport.de/2017/01/11/kommunistischer-widerstand-in-leipzig-1943/
+ at first hope for a fast end, but that did not happen
+ no more public actions, but holding up conntact to allies
+ Lost battle of Stalingrad for Germany, new hope and continuation of resistence
+ 4 different groups, connected in discussion and so on, but not really connected because of different political views and the difficulty of the illegal work

** First group
 + Georg Schumann, Otto Engert, Kurt Kresse
 + WW II is an imperialistic war, allies also responsible for the war
 + because of that, they wanted to fight together with the sojets against the allies
 + later demanded that the west victors should aknowledge the independece of Germany

** Second Group
 + William Zipperer, Arthur Hoffman, Karl Jungbluth
 + thought that that plan was follish and assumed a weakness of the left movement
 + demanded instant end of the war and the creation of a frontline of all antifashistic powers to build a democratic afterwargermany

** Third Group
 + Rudolf Hardtmann, Kurt Rosberf, Krl Plesse
 + demanded instant, no compromiss end of the war
 + Hardmann imprisoned in dezember of 1942, for two years, after that into the KZ
 + under torture he disclosed othe resistence members **(maybe have to rescue him)**

** Fourth Group / Internationale Antifaschistisches Komitee (IAK)
 + e.g. Family Hauke, sowjet laborprisoners and POWs
 + planed to act, when the red army arrived
 + 31.05.1944 IAK was "caught"



 + after the devestating bombing of leizpig the spread out fliers with the call to resistence, interrupt the warproduction and seek shelter in case of an attack instead of staying at the workplace
 + multiple V-Maenner in the groups
 + torture and blackmailing of the memebers
 + Summer of 1944 coordinated an country wide strike against communist resistence
 + a lot of memebers did not disclose unknown members and only admit to already known facts
 + only Hardtmann also disclosed other stuff -> tryed suicide on the 29.09.1944 out of dispair
 + a lot of death sentences in the dezember of 1944
 + leaders were executed on the 11. january 1945 in the yeard of the dresdner landgerichts
 + some could flee in the 13th February of 1945 because a bombing got the prison (Alfred Schellenberger, Frit Gietzelt)
 + Max hauke and Carl Riter were not able to be executed, because their record were burned **(taks for the gang)**

* Plan first season
1. get to a resistence group
2. initial test, get send to steal something
3. have to find out, where person is held, maybe attend party and gather intel
4. free CI (he knows how to attack)
5. attack and overtake Erla Werke/MIMO

* Story

** Get to a resistence group
 + can decide how their morning looks (ask them, what they are doing)
 + if there is an opportunity to convince them to go to the address, do it, otherwise there is a letter under the door, which reads:
   #+BEGIN_QUOTE
   Seid gegruest werter Leser,

   Sie wundern sich vielleicht, warum sie diesen Brief bekommen haben. Dies werde ich ihnen nicht hier erzaehlen.
   Wenn sie mehr erfahren wollen, dann seien sie gegen 19 Uhr unter der Bruecke ueber die Parthe an der Berliner Strase und warten sie dort.
   Wenn sie jemand mit "Hello there" anspricht, antworten sie "You are a bold one". Dies ist eine Art Passwort.
   Seien sie vorsichtig, dass ihnen niemand folgt.   

   Die Astoria Gesellschaft
   #+END_QUOTE
 + if the gang decides to go there at 19'o clock, they might have to hide, dice roll (7 oder weniger) if there is a patrol
 + players meet each other, have time to talk with eachother
 + after 15 minutes nobody comes, after 30 min still nobody, after 40 minutes somebody casually walking approaches from the side
 + the person wears a long cloak with a hoad
 + as she approaches a hand appears from the cloak and a little flame dances on it, spending a bit of light
 + she says **"Hello there"** in a female voice
 + after the playsers answer she says: 
 #+BEGIN_QUOTE
 Mein Name is Thalia, es freut mich, dass ihr der Einladung nachgekommen seid.
 Was ihr jetzt seht, ist streng geheim. Wenn ihr auch nur einer uneingeweihten Person etwas erzaehlt, ohne Erlaubnis oder triftigen Grund, wird es Konsequenzen geben.
 Mehr erfahrt ihr drinnen
 #+END_QUOTE
 + she waves with her hand at the wall of the sewer and the bricks start to move, clicing and clacking

* People Index

** Thalia
*** Allgemeine Infos

 | Echter Name | Sarah Schuchard |
 | Geschlecht  | Weiblich        |
 | Alter       | 28              |
 | Groese      | 1,63m           |
 | Gewicht     | 60kg            |
 
*** Rolle in der Astoria Gesellschaft
  + kuemmert sich um Anheuern und Auftraege
  + Involviert aufjedenfall
